services:
  jekyll:
    image: arm64v8/ruby:3.0
    command: >
      bash -c "
        gem install bundler jekyll &&
        bundle install &&
        bundle exec jekyll serve --host 0.0.0.0 --watch"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=development