name: Fetch Bluesky Posts

on:
  schedule:
    # Run daily at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual trigger
  
permissions:
  contents: write

jobs:
  fetch-posts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests python-dateutil
        
    - name: Fetch Bluesky posts
      run: python scripts/fetch_bluesky_posts.py
      env:
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _ideas/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Bluesky ideas feed $(date '+%Y-%m-%d %H:%M')"
          git push
        fi